

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile  # Usa una imagen slim/alpine en tu Dockerfile para FastAPI
    ports:
      - "8080:8000"  # Puerto externo 8080 -> interno 8000
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    env_file:
      - .env

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "5439:5432"  # Puerto externo 5439 -> interno 5432 (estándar de PostgreSQL)
    restart: unless-stopped

volumes:
  postgres_data:
