<%doc>
    Alembic migration script template.
    This script is generated by Alembic and is used for database migrations.
</%doc>

from alembic import op
import sqlalchemy as sa

def upgrade():
    pass

def downgrade():
    pass
